### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by a2800276** [ubinity/webpcsc-firebreath#1]
I was running into some problems trying to biuld on Linux (Ubuntu 12.04 LTS), I think I'm following the instructions closely, but I'm running into difficulties at this point:

```
Copy $(FBPlugins)/cmake/Modules/FindPCSCLite.cmake into /usr/share/cmake-
2.8/Modules/ (or something like that)
```

There is no FindPCSCLite.cmake to be found and ./prepmake complains:

```
CMake Error at projects/PCSCBridge/X11/projectDef.cmake:22 (find_package):
  Could not find module FindPCSCLite.cmake or a configuration file for
  package PCSCLite.

  Adjust CMAKE_MODULE_PATH to find FindPCSCLite.cmake or set PCSCLite_DIR to
  the directory containing a CMake configuration file for PCSCLite.  The file
  will have one of the following names:

    PCSCLiteConfig.cmake
    pcsclite-config.cmake
```

but neither of those can be found either. I'd appreciate a pointer in the right direction!
Thanks for the work this far, it looks like exactly what I've been searching for.

**Comment by ubinity** [comment]
Hi

It seems to be missing from the project - we'll fix that soon. 

In the time being you can grab it from some other place - such as https://bitbucket.org/infotermoo/memopol/src/c8f93bc037ff/cmake/modules/FindPCSCLite.cmake - and copy this to CMake modules path as listed.

**Comment by a2800276** [comment]
thanks, worked like a charm!

**Comment by ubinity** [comment]
Hi,

I added the missing file and fix the Readme according that

C/M.
